### ISSUE TITLE
Always return the stream in `HandshakeError`

### ISSUE THREAD

**Issue by bfrascher** [sfackler/rust-openssl#1069]
I would be nice to have the option to respond to a failed handshake.  E.g. in the web server context a client might have sent a http request instead of a https one.  Currently the socket will be closed unceremoniously, but from a usability standpoint it might be helpful to inform the client that they need to use https instead or at least provide them with a valid answer.

**Comment by sfackler** [comment]
If you want to specifically detect HTTP vs HTTPS requests, the more standard approach is to read the first couple of bytes of the request and see if it's a TLS handshake or not IIRC. Assuming that a handshake failure was because the stream wasn't using TLS in the first place is not going to be all that accurate.
