### ISSUE TITLE
Linux win32-x86-64-gnu cross-compiling broken

### ISSUE THREAD

**Issue by eoger** [sfackler/rust-openssl#1106]
https://github.com/sfackler/rust-openssl/commit/844c3c445ae782623b05d3489c49751565fef646 broke cross-compiling to Windows for us, we get the following message: `
error: could not find native static library 'ssl', perhaps an -L flag is missing?
`.
I can confirm that switching back to `openssl-sys` `0.9.43` fixes the problem for us.

**Comment by sfackler** [comment]
How is your cross compilation toolchain setup? Are you naming the libraries `liblibssl.a` or something?

**Comment by eoger** [comment]
We call them `libssl.lib`, here are our compiling steps: https://github.com/mozilla/application-services/blob/c0fd25a6de2ca140678784beea34503bad221b03/libs/build-openssl-desktop.sh#L77-L105

**Comment by sfackler** [comment]
Reverted the change and published 0.9.45 - sorry for the breakage!

**Comment by eoger** [comment]
Thank you!

**Comment by nanpuyue** [comment]
Sorry for the breakage.

![20191210140031](https://user-images.githubusercontent.com/1524609/70500149-c769ef00-1b55-11ea-8c8f-e6df379b5f10.png)

For the cygwin/mingw ports of ld, when using static linking to link the `xxx` library, it searches for `libxxx.a` and `xxx.lib`.

Take `libssl` as an example:
If we pass the parameter `-Wl,-Bstatic -lssl`, it searches for `libssl.a` and `ssl.lib`,
or pass the parameter `-Wl,-Bstatic -llibssl`, it searches for `liblibssl.a` and `libssl.lib`.

If we have `libssl.a` but no `libssl.lib`, `-Wl,-Bstatic -llibssl` will cause the link to fail, that's why I made that commit.

If I understand correctly, in the case of static linking, we need to detect the file name of the static library before deciding which parameter to pass.

@sfackler
