### ISSUE TITLE
missing openssl even when its installed

### ISSUE THREAD

**Issue by Nirco99** [sfackler/rust-openssl#1600]
I'm trying to run a test on vscode
and it cant find openssl package.
I tried to remove the package and re install it (using apt install pkg-config libssl-dev)
used sudo apt-get update/upgrade

earlier today I moved my wsl to E drive from C drive, restarted and then I got this error.
I'm attaching the output.

`
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `E:\solana\solana-testing\target\debug\build\openssl-sys-b70d9e821f25f4ed\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-pc-windows-msvc
  $TARGET = x86_64-pc-windows-msvc
  openssl-sys = 0.9.72

  It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
  installation. If there isn't one installed then you can try the rust-openssl
  README for more information about how to download precompiled binaries of
  OpenSSL:

  https://github.com/sfackler/rust-openssl#windows

  ', C:\Users\Nir\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.72\build\find_normal.rs:180:5
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
     1: core::panicking::panic_fmt
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
     2: core::panicking::panic_display<alloc::string::String>
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\panicking.rs:63
     3: build_script_main::find_normal::find_openssl_dir
               at .\build\find_normal.rs:180
     4: build_script_main::find_normal::get_openssl::closure$0
               at .\build\find_normal.rs:15
     5: enum$<core::option::Option<std::ffi::os_str::OsString>, 1, 18446744073709551615, Some>::unwrap_or_else<std::ffi::os_str::OsString,build_script_main::find_normal::get_openssl::closure$0>
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\option.rs:787
     6: build_script_main::find_normal::get_openssl
               at .\build\find_normal.rs:15
     7: build_script_main::find_openssl
               at .\build\main.rs:57
     8: build_script_main::main
               at .\build\main.rs:65
     9: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
The terminal process "C:\Users\Nir\.cargo\bin\cargo.exe 'test', '--package', 'solana-testing', '--lib', '--', 'test::test_send_sol', '--exact', '--nocapture'" terminated with exit code: 101.

`

**Comment by sfackler** [comment]
That build error is on Windows, so if you were installing OpenSSL via Apt I would not expect that to be picked up.

**Comment by Nirco99** [comment]
> That build error is on Windows, so if you were installing OpenSSL via Apt I would not expect that to be picked up.

yup, I used apt and every issue that resembled to this problem did not help.
As I said, I'm using ubuntu.

**Comment by sfackler** [comment]
Ubuntu does not have a C:\ drive. If you are using WSL, you should run Cargo from within WSL.

**Comment by Nirco99** [comment]
> Got any solution?

> Ubuntu does not have a C:\ drive. If you are using WSL, you should run Cargo from within WSL.

*Im using WSL.
and as I said earlier today everything worked fine.

**Comment by sfackler** [comment]
I cannot speak to how vscode is deciding to invoke the compiler, but the error output you provided explicitly states that it was from a Windows x86_64 hosted Cargo:

> $HOST = x86_64-pc-windows-msvc
> $TARGET = x86_64-pc-windows-msvc

**Comment by atitttu** [comment]
i am facing the same issue i downloaded openssl and am while downloading anchor it is saying that it could not find the directory of openssl







  --- stderr
  thread 'main' panicked at 'Unable to find libudev: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"", output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Package libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'libudev' found\n" } }', /home/vinit/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.6/build.rs:53:54
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys v0.9.66`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installQLQ3rB/release/build/openssl-sys-8e6262127686c48e/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.66

  ', /home/vinit/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.66/build/find_normal.rs:174:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `anchor-cli v0.14.0 (https://github.com/project-serum/anchor?tag=v0.14.0#5017a1af)`, intermediate artifacts can be found at `/tmp/cargo-installQLQ3rB`

**Comment by emredurgunlu** [comment]
try this:
sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev

**Comment by tolvanea** [comment]
Had this problem too on native Ubuntu 22.04.  Installed the packages stated in documentation, and it still could not find the openssl. 

If others are having the same problem, easy workaround is to compile openssl from the source by using the `vendored` feature. That is, change the dependency in Cargo.toml from for example
```openssl = "0.10"```
to
```openssl = { version = "0.10", features = ["vendored"] }```

To compile openssl on ubuntu, following packages are needed:
```sudo apt-get install perl build-essential```
