### ISSUE TITLE
Update openssl-src to 300?

### ISSUE THREAD

**Issue by link2xt** [sfackler/rust-openssl#1645]
Currently openssl-sys crate references openssl-src version 111. Is there any plan to update to OpenSSL 3.0?

**Comment by sfackler** [comment]
OpenSSL 3 unfortunately has some pretty severe performance regressions. The vendored feature will use 1.1.1 until the upstream situation improves: https://github.com/sfackler/rust-openssl/pull/1578.

**Comment by amousset** [comment]
We will likely need to soon switch to openssl 3 anyway as 1.1 will reach EOL (11th September 2023).

**Comment by sfackler** [comment]
Yeah, it's probably time. OpenSSL 3.1.0 seems to have at least partially resolved the performance regressions.

**Comment by daprilik** [comment]
For folks interested in using vendored openssl 3.0 today, I've figured out a somewhat hacky approach that allows patching `openssl-src` in the crate-graph without running into cargo `[patch]` semver issues.

Create a new crate called `openssl-src-hack`, with the following `Cargo.toml` and `src/lib.rs`:

```toml
[package]
name = "openssl-src"
version = "111.25.2+1.1.1t" # !! MUST MATCH VERSION IN `Cargo.lock` !!
edition = "2021"

[dependencies]
openssl-src = "300.1.0+3.1.0"
```

```rust
pub use openssl_src::*;
```

Then, patch this crate in via `[patch]` in your project's `Cargo.toml`

```Cargo.toml
[patch.crates-io]
"openssl-src" = { path = "./openssl-src-hack" }
```

It ain't pretty... but it does indeed work, as while the `openssl-src` versions are ostensibly semver incompatible with one another (i.e: you shouldn't be able to patch a `version = "111.25.2+1.1.1t"` with a `version = "300.1.0+3.1.0"`, the actual crate-level API is totally compatible, allowing the patch to go off without a hitch.

**Comment by Sytten** [comment]
Agreed thats what I am using, I would just like to retain vendored 1.1.1 maybe under a different feature?

**Comment by sfackler** [comment]
If you want to continue using an EOL version of OpenSSL you can build it yourself.

**Comment by Sytten** [comment]
I guess that's fair, I just thought that adding a feature `vendored-1.1` would really not be a big maintenance burden and would simplify the life of some people. The current vendor setup is very nice to use and builds seamlessly as part of the larger build, something you would abruptly lose. Happy to contribute the 5 lines of code that this represents if you change your mind.

**Comment by Sytten** [comment]
> Your proposal (as-written) violates feature unification principle that all features are additive

This is not an argument, most popular crates added features like `uuid-1` and `uuid-0.9` during the transition period to ease the developer experience.

> Currently, the only way a package can enforce minimum OpenSSL versions is by failing to build when it encounters them

Its not the job a package to decide which version is used IMO. You cannot say that and say in the next paragraph that the OS should provide the openssl version. Those arguments are contrary to each other. If the binding is present you can use it and it's the responsibility of the developer to make sure they are present at runtime/link time.

> For a simple solution for you: you should pin a specific (old) version of the openssl crate and also not use vendored

Pinning will at some point be impossible when sub dependency move on and require an higher version of openssl-sys. Broad statement about why static linking is bad are unhelpful and I explained my particular use case in the past. End users don't care about that, they care that their software starts, no matter if they are on Ubuntu 20.04 or Ubuntu  22.04. Turns out APT is a mess and if you link against openssl 3 you have problems on 20.04 and if you link against 1.1 you have problems on 22.04.

I am not letting this go because I know it will cause problems if this transition is not handled correctly. I am not trying to be pedantic for the sake of it.

**Comment by Skepfyr** [comment]
@Sytten I may be wrong but I think there's a misunderstanding here, `vendored` is not the same as static linking, you can set the `OPENSSL_STATIC` environment variable at build time to statically link against a provided version of OpenSSL. `vendored` is there to provide a simple default for people who don't care, hence the pushback for adding a `vendored-1.1` feature, if you care that much then just build it against your preferred version of OpenSSL. We clearly don't want to make it easy to link against an EOL version of OpenSSL so don't want a `vendored-1.1` long term. Granted this will make building against a static openssl-1.1 harder, but it's definitely won't be impossible.

Additionally, I suspect we will keep testing openssl-sys against OpenSSL 1.1.1 for a long time, definitely while it's still shipped with major distros, so you don't need to worry about losing support entirely.

**Comment by micolous** [comment]
@Sytten I'm going to rearrange your points here, because I think it'll help.

> [...] Broad statement about why static linking is bad are unhelpful and I explained my particular use case in the past. End users don't care about that, they care that their software starts, no matter if they are on Ubuntu 20.04 or Ubuntu 22.04. [...] I am not letting this go because I know it will cause problems if this transition is not handled correctly. I am not trying to be pedantic for the sake of it.

I understand loud and clear that you deeply care about your end-users' experience, and there was never any doubt in my mind of that. It was absolutely not my intention to solicit an emotional response.

The reason I'm making this commentary I am is because I **also** care about *my* users' experience – both end-users and developers. I don't want them to discover their OpenSSL is broken by my library crashing at runtime, or have something in their dependency chain pulling in `openssl/vendored-1.1`. Ideally, I want the person building the software to realise what they built won't work before they send it to anyone else!

> [...] Most popular crates added features like `uuid-1` and `uuid-0.9` during the transition period to ease the developer experience.

That's something different entirely – it allows packages to build with equivalent functionality on *both* versions of `uuid`, because the major version change means the types are treated differently. There's also overhead in supporting that, because you need to account for API differences between those libraries.

I didn't think it needed to be said, but to demonstrate I'm being consistent, I would argue changing which _major_ OpenSSL version is vendored is _also_ a SemVer-incompatible change... but I can sympathise with why quick action was taken. 😄 

> Its not the job a package to decide which version is used IMO.

It **is** when they're impacted by bugs in OpenSSL which make them unusable: for me, `webauthn-authenticator-rs` needs https://github.com/openssl/openssl/pull/12826. The broken routine means my program crashes at runtime without that patch. I can't change how OpenSSL is used in order to work around it without implementing a cryptographic protocol _incorrectly_.

In order to protect my users' experience, [I explicitly check to see if the feature I want is usable, and if it is **not**, then I tell them to upgrade to OpenSSL v3.0.0 or later](https://github.com/kanidm/webauthn-rs/pull/256). This _also_ means that any `vendored` feature which points at OpenSSL 1.1 (be it the current one, or a future `openssl-1.1`) breaks my software.

It's easiest for me to say "use OpenSSL v3.0.0 or later", as they can look at their distribution's package repositories and figure out what they need to upgrade to. If that patch eventually gets backported to OpenSSL v1.1, then that may be an option... but I don't see this coming any time soon. Everyone else is migrating to OpenSSL v3.x.

Once a binary is built with OpenSSL:

* [If it's dynamically linked][3], it's against `libcrypto.so.3` and `libssl.so.3`. Systems which only have OpenSSL 1.1 have `libcrypto.so.1.1` and `libssl.so.1.1` instead.
* If it's statically linked, then it doesn't matter what the system version is.

I think that what I've done meets your expectations:

> it's the responsibility of the developer to make sure they are present at runtime/link time.

If I allowed linking against versions of OpenSSL that which were provably broken, then I would be eschewing that responsibility.

Likewise, there are others [reporting][7] [issues][8] because of things that need features in OpenSSL v3.

[7]: https://github.com/sfackler/rust-openssl/issues/1645#issuecomment-1548135103
[8]: https://github.com/sfackler/rust-openssl/pull/1578#issuecomment-1120686987
 
> Turns out APT is a mess and if you link against openssl 3 you have problems on 20.04 and if you link against 1.1 you have problems on 22.04.

I think [@Skepfyr is correct here](https://github.com/sfackler/rust-openssl/issues/1645#issuecomment-1589329679) – this shouldn't matter if you're vendoring *and* have statically linked them, and you should be able to freely use _either_ OpenSSL version on _either_ distribution.

[`OPENSSL_STATIC` will explicitly override whether `openssl-sys` uses static or dynamic libraries][0], [`openssl-src` builds OpenSSL statically][1], and [`openssl-sys` will default to using dynamic libraries if both are present][2].

I was unable to reproduce the symptoms you saw with the `openssl` crate tests on a Linux machine with OpenSSL 3:

```sh
$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

$ git clone https://github.com/sfackler/rust-openssl.git
$ cd rust-openssl

## Build vendored version
$ cargo test -p openssl --features vendored
   Compiling openssl-sys v0.9.88 (~/rust-openssl/openssl-sys)
   Compiling openssl-macros v0.1.1 (~/rust-openssl/openssl-macros)
   Compiling openssl v0.10.54 (~/rust-openssl/openssl)
    Finished test [unoptimized + debuginfo] target(s) in 35.97s
     Running unittests src/lib.rs (target/debug/deps/openssl-986641eebe96ea17)
[...] tests pass

## Check dynamic linkages
$ ldd target/debug/deps/openssl-986641eebe96ea17
	linux-vdso.so.1 (0x00007ffc4ffac000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0fbcb5f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0fbc519000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0fbc31e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0fbcb96000)
## Verify presence of OpenSSL in binary
$ strings target/debug/deps/openssl-986641eebe96ea17 | grep -E "OpenSSL.+202"
OpenSSL 1.1.1u  30 May 2023

## Build system linked version
$ cargo test -p openssl
   Compiling openssl-sys v0.9.88 (~/rust-openssl/openssl-sys)
   Compiling openssl v0.10.54 (~/rust-openssl/openssl)
    Finished test [unoptimized + debuginfo] target(s) in 6.31s
     Running unittests src/lib.rs (target/debug/deps/openssl-987f335285143245)
[...] tests pass

## Check dynamic linkages, uses system OpenSSL
$ ldd target/debug/deps/openssl-987f335285143245
	linux-vdso.so.1 (0x00007ffee91d9000)
	libssl.so.3 => /lib64/glibc-hwcaps/x86-64-v3/libssl.so.3.0.8 (0x00007fa479960000)
	libcrypto.so.3 => /lib64/glibc-hwcaps/x86-64-v3/libcrypto.so.3.0.8 (0x00007fa479400000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa479d1c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa479879000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa479205000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa479d53000)
	libz.so.1 => /lib64/glibc-hwcaps/x86-64-v3/libz.so.1.2.13 (0x00007fa479d00000)

## Verify absence of OpenSSL in library
$ strings target/debug/deps/openssl-987f335285143245 | grep -E "OpenSSL.+202"
[no hits]

## Verify that would find the OpenSSL version string
$ strings /lib64/glibc-hwcaps/x86-64-v3/libcrypto.so.3 | grep -E "OpenSSL.+202"
OpenSSL 3.0.8 7 Feb 2023
```

You can verify how your own binaries are built the same way, and [the file names will show you whether you're linked against OpenSSL v1.1 or v3][3]. If you're able to reproduce the issue and trace it down to a problem in the `openssl-*` crates, I'd suggest you open another bug for this, so you can get migration to OpenSSL v3 unblocked.

On a side note, I'm particularly cautious about vendoring after dealing with clients who were compromised as a result of enterprise application software vendors bundling years-old versions of software with well-known security vulnerabilities – even on the latest version of that package configured according to the vendor's recommendations.

Generally speaking, application developers have a responsibility to ensure that they are patching any _bundled_ dependencies (whether that be dynamic or static libraries, or Rust package dependencies) in a timely manner. This is especially important in the Tauri ecosystem, which requires careful enforcement of boundaries between web and local content, and defence in depth is the best practice.


[0]: https://github.com/sfackler/rust-openssl/blob/006afe98c7c3fa71c3d2ab55099a520b2168f8d4/openssl-sys/build/main.rs#L369-L376
[1]: https://github.com/alexcrichton/openssl-src-rs/blob/a9b8f74f23b3f39c8fb0a7dc233eba6e3919fc51/src/lib.rs#L157-L159
[2]: https://github.com/sfackler/rust-openssl/blob/006afe98c7c3fa71c3d2ab55099a520b2168f8d4/openssl-sys/build/main.rs#L413-L416
[3]: https://github.com/openssl/openssl/blob/master/INSTALL.md#notes-on-shared-libraries

**Comment by wez** [comment]
What's preventing https://github.com/sfackler/rust-openssl/pull/1925 from being merged and released?

**Comment by amousset** [comment]
Investigating the failing tests and fixing what's broken, mainly.
