### ISSUE TITLE
Explain differences between openssl and openssl-sys

### ISSUE THREAD

**Issue by frewsxcv** [sfackler/rust-openssl#169]
There are two Crate projects in this repository, yet (as far as I know) there's not a clear distinction between them. Might be nice to put a sentence or two in the README describing the differences

**Comment by jimmycuadra** [comment]
This is my understanding from looking through the code:

The openssl-sys crate is the glue that connects the C code in the OpenSSL library to Rust. It has a more or less one-to-one mapping with the types and functions in OpenSSL. These are all unsafe interfaces. The openssl crate is a higher-level library that intends to provide safe, idiomatic Rust code for performing the same types of operations that you'd otherwise use OpenSSL for directly. While openssl-sys just needs to make everything in OpenSSL available to Rust code, openssl will take some effort and API design to eke out a good interface for Rust programmers.

If a maintainer of the project can confirm that my understanding is correct, I can open a PR to add some docs explaining this.
