### ISSUE TITLE
Work on sockets instead of MemBio

### ISSUE THREAD

**Issue by manuels** [sfackler/rust-openssl#197]
I was just investigating if I can implement a SslStream working on a SocketBio instead of MemBio to make SSL_pending work reliably. What is actually the reason why MemBio is used instead of directly a SocketBio? Is it to make the code more versatile.
Would you accept a pull request to add SocketBio (using AsRawFd) in addition to MemBio?

**Comment by sfackler** [comment]
When the ssl module was written, it wasn't possible to extract a file descriptor from Rust's IO types so everything had to go through the extra layer of indirection of MemBio. Since this is now possible in modern Rust, I think it absolutely makes sense to support it, probably even as the default option. Maybe something like this:

```rust
impl<S> SslStream<S> {
    fn new<S: AsRawFd>(stream: S) -> Result<SslStream<S>> { ... }

    // This name is not great...
    fn new_wrapped<S: Read+Write>(stream S) -> Result<SslStream<S>> { ... }
```

**Comment by sfackler** [comment]
I'd also want to make sure we have a good story on windows, though. `AsRawFd` is a unix-only trait, and windows versions of Rust have a version that returns a `HANDLE` instead.
