### ISSUE TITLE
Asynchronous IO?

### ISSUE THREAD

**Issue by cmr** [sfackler/rust-openssl#249]
It's hard to tell right now whether it's safe to pass a non-blocking socket into `SslStream`. It's critical that it does not explode when `write` or `read` fails with `WouldBlock`.

**Comment by sfackler** [comment]
I'm not sure what will happen for an `SslStream` constructed with the `connect_generic` and `accept_generic` methods, but one constructed with `connect` or `accept` simply gives the underlying file descriptor to OpenSSL and socket-level errors like `EWOULDBLK` will be propagated up through just fine.

**Comment by cmr** [comment]
Currently there are panics corresponding to SSL_ERROR_WANT_READ and SSL_ERROR_WANT_WRITE that get tossed up when the socket returns EWOULDBLOCK. This is a normal "error" that happens whenever the state machine can't make progress.

**Comment by sfackler** [comment]
Seems like the easy solution would be to translate those to an error with the `WouldBlock` kind.

**Comment by cmr** [comment]
Yup.

**Comment by bvinc83** [comment]
I'm currently looking at what it would take to make openssl work with async io.

It seems fairly straight forward to create a new type of SslError for SSL_ERROR_WANT_READ and SSL_ERROR_WANT_WRITE and return those if they happen on any function that may return an SslError.

The read and write from std::io::{Read,Write} on SslStream return an io::Result.  These can be easily modified to return a wrapped io error like this:
```rust
Err(io::Error::new(io::ErrorKind::WouldBlock, SslError::WantReadError))
```
This seems great, but I'm not sure how the caller would be able to tell if it's a WantReadError or a WantWriteError.  io::Error has a method called into_inner that returns a ```Box<Error + Send + Sync>```.  With that, they can only get an error description string.  Maybe there's something I don't understand here.  Maybe the caller can't use these trait methods if they really care about if SSL gives a WantReadError or WantWriteError.  Anyone have any good ideas?

Also, trait methods like write_all are problematic since they don't even give the caller a way to know how many bytes were written before it failed.

An even bigger problem are the wrapping functions like accept and connect.
```rust
pub fn accept<T: IntoSsl>(ssl: T, stream: S) -> Result<SslStream<S>, SslError>
```
A stream like TcpStream is a move type.  Functions like accept will wrap it with an SslStream.  If it fails, which it will with non-blocking IO, then the stream is lost.  It seems like any function that wraps a moveable type should be a function that never fails.  It seems like this needs to be turned into a two step process.  1.  Wrap the stream with an SslStream that never fails.  2.  Call accept as a method on SslStream.

**Comment by sfackler** [comment]
A nonblocking API may want a separate stream type than `SslStream` which may not end up implementing `Read` and `Write` directly to ensure that WANT_READ and WANT_WRITE statuses propagate directly.

You can downcast from a Box<Error> to the concrete type but that's a not great thing to have to do regularly.

**Comment by bvinc83** [comment]
I wrote some code to get some discussion going.  This would allow async io by adding a differnet kind of stream.

https://github.com/bvinc83/rust-openssl/commit/7dd08a1e710ed2ed07c4edc77ae6a6cf4e635cd6
* I added WantReadError and WantWriteError to SslError to easily match on it, otherwise the caller would just get a StreamError.
*  a wrap() function is separate from accept, connect, and init_bio, so that any of those can fail and you won't lose the stream.

I don't really like the addition of a new type of stream though.  What if ```SslStream``` just had two lowlevel methods on it, ```ssl_read``` and ```ssl_write``` that used ```SslError```?  But if you did this, everyone's code would need to change so that ```accept``` and ```connect``` were just methods that could fail without losing the stream.  Would you be willing to change the ```accept``` and ```connect``` methods for ```SslStream``` so that it could work with non-blocking IO?

**Comment by sfackler** [comment]
Separate `ssl_read` and `ssl_write` methods would work for me.

Is changing `accept` and `connect` to return the stream on error what's actually going to work for this use case? It seems like it wouldn't since your only option would be to re-pass the stream to `accept` or `connect` again, which will I think not do what you want since it'll just restart the negotiation rather than continuing it.

**Comment by bvinc83** [comment]
Maybe I'm misunderstanding something, but when ```SSL_accept``` or ```SSL_connect``` fail with ```SSL_ERROR_WANT_READ``` or ```SSL_ERROR_WANT_WRITE```, you must repeat the call once you've waited for the proper condition.  That's what the documentation says to do, so I assume that, in that case, it doesn't start the negotiation all over again.

Also, I want to be clear about "returning the stream on error".  Simply providing a way that the stream can be returned in the case of an error doesn't seem to work.  Move semantics on things like TcpStream will prevent it from going in two different directions (error vs success).  The only thing that seems to make sense is that ```accept``` and ```connect``` are &self methods on an SslStream that already wraps the TcpStream.  I can't come up with any other way.

**Comment by bvinc83** [comment]
The NonblockingSslStream that was added looks pretty awesome!  It looks pretty well designed, and much better than my sample code.

I'll use it and see if I have any problems.

My first thoughts are that it's pretty strange that the connect and accept functions just assume success.  The SSL documentation says that if connect/accept returns WANT_READ or WANT_WRITE, it should be repeatedly called until it returns with a success or failure.  The current code doesn't allow this, but maybe it doesn't matter?  Also, the current code doesn't allow you to figure out if connect/accept completed successfully or not.  You just have to read/write until you see an error?  I'm not sure if this is a big deal or not.

**Comment by sfackler** [comment]
It is a bit weird, but does make the API a lot simpler. Otherwise you need the weird intermediary "in the middle of the initial handshake" state.

**Comment by bvinc83** [comment]
The ```NonBlockingSslStream``` is great.  The one problem I see is that it's still impossible to use this library on top of mio on Windows.  This is because ```TcpStream``` on mio on Windows doesn't implement ```AsRawSocket```, seemingly with good reason (it uses io completion ports).  If you use ```NonBlockingSslStream``` on Windows, you have to abandon mio and use select(), which only works on sockets (on Windows) and isn't appropriate for everyone's event loops.

It's unfortunate that even using the ```IndirectStream```, there is still no way to use this library on top of mio, because as soon as the stream returns ```EWOULDBLOCK```, everything fails.

**Comment by sfackler** [comment]
v0.7.2 Adds nonblocking suppport directly in `SslStream`, and should (I think?) support windows as well.
