### ISSUE TITLE
assertion failed: `(left == right)` in crypto/hmac.rs:94

### ISSUE THREAD

**Issue by Turbo87** [sfackler/rust-openssl#303]
I am trying to run a local instance of [crates.io](https://github.com/rust-lang/crates.io). Now as soon as I request anything I'm getting a thread panic and the request fails with the following message:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `-1869604155`, right: `1`)', /Users/tbn/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/openssl-0.6.7/src/crypto/hmac.rs:94
```

I am trying this on OSX 10.11 and with openssl installed via homebrew. The command to complie the application (and this lib as its dependency) is `OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include cargo build`

Any ideas what I'm doing wrong here?

/cc @alexcrichton

**Comment by sfackler** [comment]
If I had to guess I'd say that you're building against OpenSSL > 1.0 and running against OpenSSL < 1.0. Did you statically or dynamically link to OpenSSL? If you dynamically linked, you'll need to adjust your `DYLD_LIBRARY_PATH` to point to `/usr/local/opt/openssl/lib` to make the linker find that instead of the ancient version of openssl that ships with OSX.
