### ISSUE TITLE
Double-drop of `try_clone()`ed streams

### ISSUE THREAD

**Issue by llasram** [sfackler/rust-openssl#325]
I'm not familiar enough with OpenSSL/openssl-rust to have narrowed this down futher yet, but there appears to be a double-drop/-free or related error with the use of `try_clone()`ed `SslStream` structs.  I have assemled a [minimal reproduction repo][reproduction], execution of which produces a segmentation fault.

[reproduction]: https://github.com/llasram/openssl-2xdrop-rust

**Comment by sfackler** [comment]
Looking into this, the `SslStream::{try_clone,clone}` methods have always been conceptually broken - the underlying `Ssl` object is going to be shared by the two copies and it always points to the same stream. Before it would probably just be racy and break in weird ways but now it'll crash.

These methods need to go away - I guess we could just cut a breaking 0.8 release, which is unfortunate since that tends to cause large painful ripples through downstream.

I think for now I might replace the implementations with a `panic!("this method was totally broken and will be removed.")`? It's certainly less bad than hitting a null pointer.

**Comment by sfackler** [comment]
It actually looks like I can adjust things so it will be "no more" wrong than it was previously. I'll do that, deprecate the methods and we'll remove them in 0.8.

**Comment by sfackler** [comment]
Ok, I pushed up a commit that reduces the brokenness to what it was in 0.7.0. I'll publish that and we'll wait a while to delete these methods in an 0.8 release.
