### ISSUE TITLE
Test on multiple versions of OpenSSL in Travis CI

### ISSUE THREAD

**Issue by frewsxcv** [sfackler/rust-openssl#382]
From what I can tell, Travis CI is just testing on whatever the system has installed. It might be worth expanding testing to 0.9.8 and 1.0.0 (and 1.1.0?)

As an example, here is what pyca/cryptography does:

https://github.com/pyca/cryptography/blob/master/.travis.yml#L26-L40

https://github.com/pyca/cryptography/blob/master/.travis/install.sh

**Comment by sfackler** [comment]
We're picking up 0.9.8 from the OSX bots. On Linux, we build 1.0.2g - I believe because the version that comes on Travis's images has some bugs in the DTLS implementation that breaks a couple tests: https://github.com/sfackler/rust-openssl/blob/master/openssl/test/build.sh.

We don't test on 1.1.0 because it broke a ton of APIs and we won't build at all against it. (I'm actually a bit worried about this - figuring out a 1.1.0 story seems important. How are distros going to handle 1.1.0, anyway?)

**Comment by sfackler** [comment]
I'd be on board with testing other version variants as well, though we'd probably want to refactor the set of builds - we're already pushing it on Travis parallelism-wise.
