### ISSUE TITLE
Coordinate openssl-sys release with major consumers

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-openssl#466]
Breaking -sys upgrades are a coordination pain, so we'll want to make sure that curl, hyper, etc are ready to go.

**Comment by cuviper** [comment]
Here's Cargo's current dependency tree, pruned for paths leading to openssl:

```
cargo v0.14.0
├── crates-io v0.4.0
│   └── curl v0.3.7
│       ├── curl-sys v0.2.3
│       │   └── openssl-sys v0.7.14
│       └── openssl-sys v0.7.14 (*)
├── curl v0.3.7 (*)
├── git2 v0.4.4
│   └── libgit2-sys v0.4.5
│       ├── libssh2-sys v0.1.39
│       │   └── openssl-sys v0.7.14 (*)
│       └── openssl-sys v0.7.14 (*)
├── git2-curl v0.5.0
│   └── curl v0.3.7 (*)
├── libgit2-sys v0.4.5 (*)
└── openssl v0.7.14
```

**Comment by sfackler** [comment]
@alexcrichton 
* curl-rust and git2-rs depend on the probe module that has been removed.
* cargo's SHA256 implementation will be have to be updated for some API changes on the openssl side.
* Docs for all three need to be updated.

@seanmonstar 
* hyper depends on 0.7

@reem 
* iron depends on 0.7 via hyper.

I think that may be the big ones?

**Comment by alexcrichton** [comment]
Yeah curl and git2 shouldn't be hard to update, I'll just vendor that probe logic somewhere and leave it. Dealing with Cargo is going to be difficult because it still needs to either compile and link against the system OpenSSL on OSX or statically link a newer version, both of which won't be trivial to update for unfortunately.

I'm fine publishing new versions of openssl* crates though without blocking on that, seems like great updates regardless.

**Comment by seanmonstar** [comment]
As I mentioned in IRC, I'd rather not bump hyper 0.9 to 0.10, and instead release async hyper as 0.10.

What I've done instead is spent some time on a client crate, https://github.com/seanmonstar/reqwest. It currently is working with native-tls. I could publish a version of it as soon as native-tls is published.

The idea is that I assume most people using HTTPS are using in the Client, since most terminate TLS for their servers using nginx. I've also always felt there could be a higher level client crate, that includes things like JSON support, multipart forms, auto gzip decoding, and the like. I'd recommend people using `hyper::Client` to swap to `reqwest`, which would have very little API breakage, and they would gain new easy features. It'd also mean that when async hyper does release at 0.10, `reqwest` can upgrade internally, and still expose a synchronous Client for people who want it (but with proper timeouts (no timeouts on to_socket_addrs in std)), and an async Client as well.

**Comment by DemiMarie** [comment]
@seanmonstar I don't think we necessarily want to assume that nginx is used for TLS termination on servers.  Hyper is so fast that nginx could easily impose a noticeable overhead, and tokio-based hyper should be even faster.

**Comment by seanmonstar** [comment]
@DemiMarie I'm talking about hyper that is published to crates.io (v0.9). It uses synchronous IO, and its thread strategy leaves it easy to DOS, so many people put nginx in front of it. With asynchronous IO, I absolutely hope that people can deploy it without nginx. This issue is aimed at published hyper, not what is in development.

**Comment by ddt-tdd** [comment]
@seanmonstar I use hyper as a secured local service to give access to the Belgium eId smartcard.  Using JS and CORS, a web application is able to talk hardware devices (like smartcards) through a webservice on the localhost. This as an alternative to Java plugin or extensions, for which each browser has its own distribution.This client software should use SSL to prevent the browser from complaining and it is best written in Rust to prevent buffer overflow attacks.
So, I forked the hyper server and tried to update the SSL of sfackler, but this was not easy and I didn't succeeded yet. So any help from you or @sfackler would be nice to upgrade the SSL in hyper.

**Comment by euclio** [comment]
@ddt-tdd I already created a PR for hyper to upgrade OpenSSL at hyperium/hyper#940. See @seanmonstar's response in that PR.
