### ISSUE TITLE
Failing to compile against Openssl 1.0.2k built with no-ec2m

### ISSUE THREAD

**Issue by ajroetker** [sfackler/rust-openssl#600]
platform: x86_64-pc-windows-gnu
rust: 1.15.1
openssl: 1.0.2k (Configured with no-ec2m)

Not sure what I'm doing wrong here but when trying to compile against rust-openssl-0.9.9 I'm seeing the following error at the final gcc calls:

```
= note: C:\cygwin64\var\tmp\tmp.20T4aqC2hk\puppet-code\target\debug\deps\libopenssl-3e666053462ffb12.rlib(openssl-3e666053462ffb12.0.o): In function `openssl::ec::{{impl}}::components_gf2m':
C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.9.9\src/ec.rs:76: undefined reference to `EC_GROUP_get_curve_GF2m'
```

As far as I can tell that symbol *isn't* defined because our openssl is built with no-ec2m aka the OPENSSL_NO_EC is defined and those symbols don't make it into the header files (they're wrapped in an `ifndef OPENSSL_NO_EC`.

It looks like the crate handles `OPENSSL_NO_EC` in some cases, e.g. https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/ossl10x.rs#L421. Do some of EC functions in https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/lib.rs#L1530 need to also be conditionally compiled (similarly with their calls in openssl/src/ec.rs) or am I offbase and my error has come from elsewhere?

Thanks for the help!

**Comment by ajroetker** [comment]
Also I confirmed that building openssl without the no-ec2m specified solves the problem.

**Comment by sfackler** [comment]
I'm assuming the behavior difference you're seeing is due to differences in how the Windows and Linux linkers work - the Linux one is apparently okay with an unresolved symbol in a function that is never called, and Windows isn't.

The general policy right now is to deal with `OPENSSL_NO_FOO` on an on-demand basis - there are basically an infinite number of such toggles and I don't really want to try to deal with them all :). I'd be more than happy to take a PR adding the right cfgs. You'll want to cfg-off both the extern definitions in the sys crate as well as the wrappers in the non-sys crate.
