### ISSUE TITLE
Verify X509 signature

### ISSUE THREAD

**Issue by Anton-4** [sfackler/rust-openssl#630]
As verify.rs in X509 is empty, is there a way to verify the signature of an X509 certificate using sign::Verifier?

**Comment by sfackler** [comment]
It's not empty - it reexports https://github.com/sfackler/rust-openssl/blob/master/openssl/src/verify.rs

**Comment by Anton-4** [comment]
My apologies, this X509VerifyParamRef is used by SslRef, is there another way to just verify the signature without using Ssl? Or if there is not, is there is an easy way to extract the data from an X509 over which the signature is calculated. I will gladly add the code myself if you can point me in the right direction.

**Comment by bluejekyll** [comment]
I was looking at something akin to what you're asking about, I think. Take a look at this branch: https://github.com/sfackler/rust-openssl/compare/master...bluejekyll:verify_cert#diff-3c34fc20efa0aafbeb82758e99f718e1R79

I pulled the PR because I wasn't 100% sure it was needed. I think you could potentially do the same thing by building up a new SslContext and using that...

**Comment by Anton-4** [comment]
I think it would make X509 nicely self-contained and I can certainly use it.
If it is not merged in I will add your code to my project, thanks @bluejekyll !

**Comment by bluejekyll** [comment]
If you find this useful, let me know. Just double check that I didn't leave anything out. If it's useful I'll push a PR for it and see about getting it merged in.

The reason I dropped it is because the complexity of building up the parameters of the function are high enough, that it might be just as much overhead to just build up a new SslContext and use that instead.

**Comment by Anton-4** [comment]
Good point, I will probably use it tomorrow and will let you know how it goes

**Comment by Anton-4** [comment]
@bluejekyll I used verify_cert with success. My implementation was very similar to the test you wrote. In my case the parameters were simple because I'm making demoware, so I can't really speak for the general case. It can hardly hurt having the extra code in the project especially when it can save someone a lot of time. Thank you again @bluejekyll for telling me about your code.

**Comment by bluejekyll** [comment]
did you need to make any change to the implementation? If not, then I'll reopen the PR.

@sfackler do you want this?

**Comment by Anton-4** [comment]
No changes needed to be made.

**Comment by stbuehler** [comment]
I think #602 (the original PR by bluejekyll) was superseeded by #861 which got merged; so this can be closed afaict.
