### ISSUE TITLE
LibreSSL v2.6.1 *does* support ALPN, find a way to make rust-openssl know this?

### ISSUE THREAD

**Issue by yarwelp** [sfackler/rust-openssl#690]
LibreSSL has had support for ALPN for quite a while but due to configuration of the openssl and openssl-sys crates, they build without ALPN support even though LibreSSL has it.

By simply stripping away cfg-lines from the source of rust-openssl one by one and redoing the cargo build of the program I was trying to use after each time I was eventually able to get a working version.

Obviously I am not suggesting that you remove the cfg lines but the point is to show that it works.

Perhaps you could think up a way to actually feature-test for ALPN instead of hardcoding selected versions of OpenSSL that are known to support it, such that new versions of OpenSSL and LibreSSL can be used without having to make any modifications?

**Comment by sfackler** [comment]
We used to have separate Cargo features for each thing that wasn't supported by all versions of OpenSSL, but it was a bit of a mess. We've since migrated to features per version of OpenSSL. We could do the same for relevant libressl things (i.e. add a `libressl-v261` feature here: https://github.com/sfackler/rust-openssl/blob/master/openssl/Cargo.toml#L17)
