### ISSUE TITLE
Something weird is happening with headers in the vcpkg Windows build

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-openssl#889]
https://ci.appveyor.com/project/sfackler/rust-openssl/build/1.0.2265/job/6fsrfhgvsurfc251

It looks like we're ending up with 2 copies of a bunch of stuff?

**Comment by sfackler** [comment]
It looks like this was the first instance of this failure, and I don't think there were changes in that which would affect the headers that are included there.

https://ci.appveyor.com/project/sfackler/rust-openssl/build/1.0.2247/job/j2be9jgfjwtb6i4y

Might have been a change in the vcpkg setup?

**Comment by sfackler** [comment]
It also doesn't appear on our builds that use an OpenSSL from slproweb rather than vcpkg.

**Comment by ras0219-msft** [comment]
We did make a change to openssl to pull in `winsock2.h` instead of `winsock.h`. This is the recommended header on MSDN[1], supported since pre-XP.

However, for legacy reasons `windows.h` will sometimes pull in `winsock.h`. The best solution for you would be to simply define `WIN32_LEAN_AND_MEAN` which would avoid pulling in `winsock.h` as well as making your builds faster, however the minimal-impact change is probably to `#define _WINSOCKAPI_` (the header guard for the old winsock header).

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/ms740560(v=vs.85).aspx

**Comment by sfackler** [comment]
`WIN32_LEAN_AND_MEAN` worked, thanks!
