### ISSUE TITLE
Doesn't build on macOS with nix

### ISSUE THREAD

**Issue by bemeurer** [sfackler/rust-openssl#948]
On macOS 10.13.5 using [nix](https://nixos.org/)  as a package manager, this fails to build.
```
error: failed to run custom build command for `openssl-sys v0.9.33`
process didn't exit successfully: `/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installKwP3p6/release/build/openssl-sys-22c4ac495d4fc1c4/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"
--- stderr
thread 'main' panicked at '
Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.
Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.
    $HOST = x86_64-apple-darwin
    $TARGET = x86_64-apple-darwin
    openssl-sys = 0.9.33
It looks like you're compiling on macOS, where the system contains a version of
OpenSSL 0.9.8. This crate no longer supports OpenSSL 0.9.8.
As a consumer of this crate, you can fix this error by using Homebrew to
install the `openssl` package, or as a maintainer you can use the openssl-sys
0.7 crate for support with OpenSSL 0.9.8.
Unfortunately though the compile cannot continue, so aborting.
```

Even though I install it with `nix-env -i openssl` the compilation continues to fail with the exact same error.

**Comment by sfackler** [comment]
I'm not familiar with NIx, but from the error, you don't have pkg-config installed. You can either install that or use the environment variables to point towards the Nix-installed location: https://github.com/sfackler/rust-openssl#manual-configuration

**Comment by bemeurer** [comment]
@sfackler I installed pkg-config, as well as cmake, but the issue remains. I will try to manually configure
```
error: failed to run custom build command for `openssl-sys v0.9.33`
process didn't exit successfully: `/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installhCRsEh/release/build/openssl-sys-22c4ac495d4fc1c4/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-apple-darwin
    $TARGET = x86_64-apple-darwin
    openssl-sys = 0.9.33



It looks like you're compiling on macOS, where the system contains a version of
OpenSSL 0.9.8. This crate no longer supports OpenSSL 0.9.8.

As a consumer of this crate, you can fix this error by using Homebrew to
install the `openssl` package, or as a maintainer you can use the openssl-sys
0.7 crate for support with OpenSSL 0.9.8.

Unfortunately though the compile cannot continue, so aborting.
```

**Comment by bemeurer** [comment]
After much finagling, the issue was mostly due to Nix namespaces. For anyone who might come across this in the future, make sure to install `nixpkgs.openssl` as opposed to just `openssl`.

Now I have a new issue at the final compilation step, relating to not finding libiconv, which I have installed.

```
   Compiling cargo-outdated v0.7.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/bemeurer/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/deps/cargo_outdated-b779629bdcc1ce40.cargo_outdated0.rcgu.o" "-o" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/deps/cargo_outdated-b779629bdcc1ce40" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/deps" "-L" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/build/miniz-sys-bb1ef5022c14bd86/out" "-L" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/build/libgit2-sys-e33c756b0266a709/out/lib" "-L" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv/release/build/libssh2-sys-a73a7e4bad4c2798/out/lib" "-L" "/nix/store/cmvx2hc1i1cdsbf40c63pgsq72rjynwh-openssl-1.0.2o/lib" "-L" "/Users/bemeurer/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/rustc.CxGqPEWV3J2I/liblibgit2_sys-86a2b7952ce98650.rlib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/rustc.CxGqPEWV3J2I/liblibssh2_sys-1566b4f2340200ec.rlib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/rustc.CxGqPEWV3J2I/libminiz_sys-5343b62b2f84a79e.rlib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/rustc.CxGqPEWV3J2I/libstd-68bd6c982b9b97da.rlib" "/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/rustc.CxGqPEWV3J2I/liballoc_jemalloc-71e176ef21c33764.rlib" "/Users/bemeurer/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-d4de6b08b6810717.rlib" "-framework" "CoreFoundation" "-l" "iconv" "-framework" "Security" "-framework" "CoreFoundation" "-l" "ssl" "-l" "crypto" "-l" "curl" "-l" "z" "-l" "System" "-l" "resolv" "-l" "pthread" "-l" "c" "-l" "m"
  = note: ld: library not found for -liconv
          clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: failed to compile `cargo-outdated v0.7.0`, intermediate artifacts can be found at `/var/folders/m7/gts5k4696tq8m2k0hhgyyy640000gn/T/cargo-installabMkBv`
```

**Comment by sfackler** [comment]
That's coming from some other crate.

**Comment by rben01** [comment]
> I'm running into this issue today. I tried `nix-env -i nixpkgs.openssl` but it just complains `selector 'nixpks.openssl' matches no derivations`. @lovesegfault is this the command you used?
> 
> Is there a way to bundle it, or is there some other way to work around this?

Since you're specifying the full attribute path, you need the `-A` argument: `nix-env -iA nixpkgs.openssl`

**Comment by masklinn** [comment]
For the future reader, I've also gone through this this week and I want to complement @spease's comments:

Don't waste your time on `nix-env`, `openssl` is a "multi-output" package and apparently `nix-env` has trouble with those (it might be possible to beat it into shape but I'm just a nix beginner so I've no idea yet, just that I've spent an evening trying to get the headers and libraries visible in `nix-env` and never managed it).

`nix-shell -p openssl` makes all the right bits you need visible. So `nix-shell -p libiconv openssl pkgconfig` will generate an environment with all the stuff necessary for `libgit2-sys` to build.

However you will then hit the next issue @spease encountered with `SecureTransport`, the answer to this is the realisation that nix makes Apple's frameworks available as nix packages to be explicitly requested (this realisation courtesy of @savannidgerinel who I can't thank enough for finally getting me through this), so you can just tack on `darwin.apple_sdk.frameworks.Security` to your `nix-shell`:
```sh
 nix-shell -p openssl libiconv pkg-config darwin.apple_sdk.frameworks.Security --run "cargo install cargo-edit"
```
(or leave the `--run` off and run `cargo install` inside the shell that opens).

 If an other package fails to build because of `SystemConfiguration` (e.g. `cargo-outdated`) that's at `darwin.apple_sdk.frameworks.Security`, etc... for the various other frameworks (you can find the full list at https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-sdk/frameworks.nix though the naming scheme is exactly what you'd assume so you don't really have to go through that).

I'm sure there are other and better ways to do it, but at least with that you'll have installed your cargo utilities, they'll work, and you can go on to run head-first into the next nix wall on your journey, as I'll be setting off to do myself right now.

**Comment by spease** [comment]
Wow, this is an early nix issue. Retrospectively, this should really be addressed by adding a darwin-specific dependency on the Security framework to the openssl package imho.

**Comment by masklinn** [comment]
> Wow, this is an early nix issue for me. Retrospectively, this should really be addressed by adding a darwin-specific dependency on the Security framework to the openssl package imho.

It doesn't seem to be openssl that's failing though. Instead it seems to be an issue with `git2-rs`'s build script: [if the platform is Apple and https is enabled (which I think is the default) it uses `SecureTransport`](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L139-L152), probably assuming that the macos frameworks are always available.

Obviously this assumption may not be correct using nix. libgit2 will instead [fall back to OpenSSL if `SecureTransport` is not found or not compatible](https://github.com/libgit2/libgit2/blob/7687948ac129fb097d822a3b6a8787fa037cb240/cmake/SelectHTTPSBackend.cmake#L14-L32), so the issue is not really reproducible when building libgit2 "the normal way".

**Comment by nokazn** [comment]
I ran into a similar situation.
I had to set `OPENSSL_INCLUDE_DIR` and `OPENSSL_STATIC` manually in devshell.
I hope this might help someone.

```nix
devShell = with pkgs; mkShell {
  nativeBuildInputs = [
    pkg-config
  ];
  buildInputs = [
    openssl.dev
    libiconv
  ] ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.Security
  ];
  OPENSSL_INCLUDE_DIR = (
    lib.makeSearchPathOutput "dev" "include" [ pkgs.openssl.dev ]
  ) + "/openssl";
  OPENSSL_STATIC = "0";
}
```
